### ISSUE TITLE
Calculation of weight with unit and size

### ISSUE THREAD

**Issue by Mimoja** [AndyZap/De1Win10#1]
the "unit" field is a exponent. 10^unit is the base.
So the weight is value / (10 ^ unit). 

https://github.com/AndyZap/De1Win10/blob/07c37e8bca2bec22167a2685bf3f4fda325ab82c/AcaiaProtocol20.cs#L133

**Comment by AndyZap** [comment]
Thanks, this has been fixed and tested with Lunar
